#!/bin/bash
# Download all assets for joy-homepage-clone
set -euo pipefail

BASE_DIR="/Users/bobo/Projects/joy-homepage-clone/assets"

# Create directory structure
mkdir -p "$BASE_DIR/icons"
mkdir -p "$BASE_DIR/games/platforms"
mkdir -p "$BASE_DIR/bg"
mkdir -p "$BASE_DIR/ui"

download() {
  local url="$1"
  local dest="$2"
  echo "  Downloading: $(basename "$dest")"
  if ! curl -sL -o "$dest" "$url"; then
    echo "  [FAILED] $url"
    rm -f "$dest"
  fi
}

echo "=== Core UI Icons (assets/icons/) ==="
download "https://joy.star-link-rel.cc/siteadmin/upload/img/img_dt_logo_mr1.avif" "$BASE_DIR/icons/img_dt_logo_mr1.avif"
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/1-0-55/common/_sprite/icon_dt_1ss.avif?manualVersion=1&version=v7.1.199" "$BASE_DIR/icons/icon_dt_1ss.avif"
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/1-0-common/web/home/icon_dt_pmd.webp?manualVersion=1&version=v7.1.199" "$BASE_DIR/icons/icon_dt_pmd.webp"
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/1-0-55/common/_sprite/icon_dt_1xx_wd.avif?manualVersion=1&version=v7.1.199" "$BASE_DIR/icons/icon_dt_1xx_wd.avif"
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/1-0-55/common/_sprite/icon_dt_1vip.avif?manualVersion=1&version=v7.1.199" "$BASE_DIR/icons/icon_dt_1vip.avif"
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/1-0-55/common/_sprite/icon_dt_1tg.avif?manualVersion=1&version=v7.1.199" "$BASE_DIR/icons/icon_dt_1tg.avif"
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/1-0-55/common/_sprite/icon_dt_1gd.avif?manualVersion=1&version=v7.1.199" "$BASE_DIR/icons/icon_dt_1gd.avif"
download "https://joy.star-link-rel.cc/siteadmin/upload/img/telegram.avif" "$BASE_DIR/icons/telegram.avif"
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/common/common/common/18plus.avif?manualVersion=1&version=v7.1.199" "$BASE_DIR/icons/18plus.avif"

echo ""
echo "=== Game Category Icons (assets/icons/) ==="
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/1-0-common/common/_sprite/icon_dtfl_rm_1.avif?manualVersion=1&version=v7.1.199" "$BASE_DIR/icons/icon_dtfl_rm_1.avif"
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/1-0-common/common/_sprite/icon_dtfl_by_1.avif?manualVersion=1&version=v7.1.199" "$BASE_DIR/icons/icon_dtfl_by_1.avif"
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/1-0-common/common/_sprite/icon_dtfl_dz_1.avif?manualVersion=1&version=v7.1.199" "$BASE_DIR/icons/icon_dtfl_dz_1.avif"
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/1-0-common/common/_sprite/icon_dtfl_qp_1.avif?manualVersion=1&version=v7.1.199" "$BASE_DIR/icons/icon_dtfl_qp_1.avif"
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/1-0-common/common/_sprite/icon_dtfl_zr_1.avif?manualVersion=1&version=v7.1.199" "$BASE_DIR/icons/icon_dtfl_zr_1.avif"
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/1-0-common/common/_sprite/icon_dtfl_ty_1.avif?manualVersion=1&version=v7.1.199" "$BASE_DIR/icons/icon_dtfl_ty_1.avif"
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/1-0-common/common/_sprite/icon_dtfl_cp_1.avif?manualVersion=1&version=v7.1.199" "$BASE_DIR/icons/icon_dtfl_cp_1.avif"
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/1-0-common/common/_sprite/icon_dtfl_dianjing_1.avif?manualVersion=1&version=v7.1.199" "$BASE_DIR/icons/icon_dtfl_dianjing_1.avif"
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/1-0-common/common/_sprite/icon_dtfl_douji_1.avif?manualVersion=1&version=v7.1.199" "$BASE_DIR/icons/icon_dtfl_douji_1.avif"
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/1-0-common/common/_sprite/icon_dtfl_qkl_1.avif?manualVersion=1&version=v7.1.199" "$BASE_DIR/icons/icon_dtfl_qkl_1.avif"
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/1-0-common/common/_sprite/icon_dtfl_sw_1.avif?manualVersion=1&version=v7.1.199" "$BASE_DIR/icons/icon_dtfl_sw_1.avif"

echo ""
echo "=== Background Images (assets/bg/) ==="
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/1-0-55/common/common/bg_pattern_tile.avif?manualVersion=1&version=v7.1.199" "$BASE_DIR/bg/bg_pattern_tile.avif"
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/common/common/home/cjc1_style_2_bg.webp?manualVersion=1&version=v7.1.199" "$BASE_DIR/bg/cjc1_style_2_bg.webp"
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/common/web/home/cjc1_style_1_font_sprite.avif?manualVersion=1&version=v7.1.199" "$BASE_DIR/bg/cjc1_style_1_font_sprite.avif"
download "https://joy.star-link-rel.cc/siteadmin/upload/img/2016087926218625025.avif" "$BASE_DIR/bg/2016087926218625025.avif"

echo ""
echo "=== UI Elements (assets/ui/) ==="
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/1-0-55/web/common/btn_zc1_1.avif?manualVersion=1&version=v7.1.199" "$BASE_DIR/ui/btn_zc1_1.avif"
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/1-0-55/web/common/btn_zc1_2.avif?manualVersion=1&version=v7.1.199" "$BASE_DIR/ui/btn_zc1_2.avif"
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/common/web/home/btn_sc_off_2.avif?manualVersion=1&version=v7.1.199" "$BASE_DIR/ui/btn_sc_off_2.avif"
download "https://joy.star-link-rel.cc/siteadmin/skin/lobby_asset/1-0-common/common/common/img_none_sj.avif?manualVersion=1&version=v7.1.199" "$BASE_DIR/ui/img_none_sj.avif"

echo ""
echo "=== Game Thumbnails (assets/games/) ==="
download "https://joy.star-link-rel.cc/game_pictures/g/CL/13/3/3029/default.avif?web_v=v7.1.199" "$BASE_DIR/games/game-3029.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/CL/hot/200/3/default.avif?web_v=v7.1.199" "$BASE_DIR/games/hot-200-3.avif"
download "https://joy.star-link-rel.cc/game_pictures/g/CL/200/3/2000065/default.avif?web_v=v7.1.199" "$BASE_DIR/games/game-2000065.avif"
download "https://joy.star-link-rel.cc/game_pictures/g/CL/200/3/2000074/default.avif?web_v=v7.1.199" "$BASE_DIR/games/game-2000074.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/CL/hot/127/4/default.avif?web_v=v7.1.199" "$BASE_DIR/games/hot-127-4.avif"
download "https://joy.star-link-rel.cc/game_pictures/g/CL/1006/3/10060035/default.avif?web_v=v7.1.199" "$BASE_DIR/games/game-10060035.avif"
download "https://joy.star-link-rel.cc/game_pictures/g/CL/200/3/2000084/default.avif?web_v=v7.1.199" "$BASE_DIR/games/game-2000084.avif"
download "https://joy.star-link-rel.cc/game_pictures/g/CL/310/2/3100003/default.avif?web_v=v7.1.199" "$BASE_DIR/games/game-3100003.avif"
download "https://joy.star-link-rel.cc/game_pictures/g/CL/200/3/2000135/default.avif?web_v=v7.1.199" "$BASE_DIR/games/game-2000135.avif"
download "https://joy.star-link-rel.cc/game_pictures/g/CL/200/3/2000087/default.avif?web_v=v7.1.199" "$BASE_DIR/games/game-2000087.avif"
download "https://joy.star-link-rel.cc/game_pictures/g/CL/75/3/750103/default.avif?web_v=v7.1.199" "$BASE_DIR/games/game-750103.avif"
download "https://joy.star-link-rel.cc/game_pictures/g/CL/310/2/3100004/default.avif?web_v=v7.1.199" "$BASE_DIR/games/game-3100004.avif"
download "https://joy.star-link-rel.cc/game_pictures/g/CL/200/3/2000104/default.avif?web_v=v7.1.199" "$BASE_DIR/games/game-2000104.avif"
download "https://joy.star-link-rel.cc/game_pictures/g/CL/200/3/2000067/default.avif?web_v=v7.1.199" "$BASE_DIR/games/game-2000067.avif"
download "https://joy.star-link-rel.cc/game_pictures/g/CL/200/3/2000054/default.avif?web_v=v7.1.199" "$BASE_DIR/games/game-2000054.avif"
download "https://joy.star-link-rel.cc/game_pictures/g/CL/9/1/90003/default.avif?web_v=v7.1.199" "$BASE_DIR/games/game-90003.avif"
download "https://joy.star-link-rel.cc/game_pictures/g/CL/33/3/330580/default.avif?web_v=v7.1.199" "$BASE_DIR/games/game-330580.avif"

echo ""
echo "=== Game Platform Icons (assets/games/platforms/) ==="
download "https://joy.star-link-rel.cc/game_pictures/p/L1/310/2/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-310-2.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/13/2/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-13-2.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/27/2/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-27-2.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/331/2/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-331-2.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/303/2/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-303-2.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/200/3/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-200-3.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/13/3/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-13-3.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/1006/3/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-1006-3.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/313/3/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-313-3.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/316/3/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-316-3.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/13/1/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-13-1.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/2/1/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-2-1.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/52/1/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-52-1.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/9/1/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-9-1.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/21/1/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-21-1.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/127/4/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-127-4.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/75/4/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-75-4.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/79/4/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-79-4.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/331/4/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-331-4.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/1020/4/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-1020-4.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/47/5/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-47-5.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/43/5/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-43-5.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/328/5/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-328-5.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/76/5/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-76-5.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/13/5/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-13-5.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/29/8/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-29-8.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/75/8/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-75-8.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/11/8/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-11-8.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/13/8/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-13-8.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/328/7/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-328-7.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/74/7/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-74-7.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/87/6/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-87-6.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/13/11/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-13-11.avif"
download "https://joy.star-link-rel.cc/game_pictures/p/L1/95/11/default.avif?web_v=v7.1.199" "$BASE_DIR/games/platforms/platform-95-11.avif"

echo ""
echo "=== Download Complete ==="
echo ""
echo "--- assets/icons/ ---"
ls -la "$BASE_DIR/icons/"
echo ""
echo "--- assets/bg/ ---"
ls -la "$BASE_DIR/bg/"
echo ""
echo "--- assets/ui/ ---"
ls -la "$BASE_DIR/ui/"
echo ""
echo "--- assets/games/ ---"
ls -la "$BASE_DIR/games/"
echo ""
echo "--- assets/games/platforms/ ---"
ls -la "$BASE_DIR/games/platforms/"
